/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configs */
        get: operations["list_configs_api_admin_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/configs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Config */
        put: operations["update_config_api_admin_configs__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Logs */
        get: operations["list_audit_logs_api_admin_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Overview */
        get: operations["dashboard_overview_api_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Books */
        get: operations["list_books_api_admin_books_get"];
        put?: never;
        /** Create Book */
        post: operations["create_book_api_admin_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_admin_books__book_id__get"];
        /** Update Book */
        put: operations["update_book_api_admin_books__book_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}/copies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Copies */
        get: operations["list_copies_api_admin_books__book_id__copies_get"];
        put?: never;
        /** Add Copies */
        post: operations["add_copies_api_admin_books__book_id__copies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}/toggle-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Book Status */
        post: operations["toggle_book_status_api_admin_books__book_id__toggle_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/copies/{copy_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Copy Status */
        put: operations["update_copy_status_api_admin_copies__copy_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Cover */
        post: operations["upload_cover_api_admin_books__book_id__cover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Audio */
        post: operations["upload_audio_api_admin_books__book_id__audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Books Excel */
        post: operations["import_books_excel_api_admin_books_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/uploads/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Upload
         * @description 上传文件访问（鉴权下发；封面后续小程序端另行开放只读路由）。
         */
        get: operations["serve_upload_api_admin_uploads__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_admin_books__book_id__questions_get"];
        put?: never;
        /** Create Question */
        post: operations["create_question_api_admin_books__book_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/questions/{question_id}/toggle-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Question */
        post: operations["toggle_question_api_admin_questions__question_id__toggle_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Question */
        delete: operations["delete_question_api_admin_questions__question_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/circulation/children/{child_id}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Child Card */
        get: operations["child_card_api_admin_circulation_children__child_id__card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/circulation/borrow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Borrow Book */
        post: operations["borrow_book_api_admin_circulation_borrow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/circulation/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return Book */
        post: operations["return_book_api_admin_circulation_return_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/circulation/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew Book */
        post: operations["renew_book_api_admin_circulation_renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/circulation/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overdue List */
        get: operations["overdue_list_api_admin_circulation_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/members/parents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Parent */
        post: operations["create_parent_api_admin_members_parents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/members/parents/{parent_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Children */
        get: operations["list_children_api_admin_members_parents__parent_id__children_get"];
        put?: never;
        /** Create Child */
        post: operations["create_child_api_admin_members_parents__parent_id__children_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/members/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Children Page */
        get: operations["list_children_page_api_admin_members_children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_admin_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_admin_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/confirm-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Payment */
        post: operations["confirm_payment_api_admin_orders__order_id__confirm_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Order */
        post: operations["cancel_order_api_admin_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deposits */
        get: operations["list_deposits_api_admin_deposits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/children/{child_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deposit */
        get: operations["get_deposit_api_admin_deposits_children__child_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/children/{child_id}/ledgers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deposit Ledgers */
        get: operations["get_deposit_ledgers_api_admin_deposits_children__child_id__ledgers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/children/{child_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Deposit Order */
        post: operations["create_deposit_order_api_admin_deposits_children__child_id__orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/children/{child_id}/supplement-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Supplement Order */
        post: operations["create_supplement_order_api_admin_deposits_children__child_id__supplement_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/children/{child_id}/deduct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deduct Deposit */
        post: operations["deduct_deposit_api_admin_deposits_children__child_id__deduct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserResponse */
        AdminUserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /** AuditLogResponse */
        AuditLogResponse: {
            /** Id */
            id: number;
            /** Actor Id */
            actor_id: number;
            /** Actor Name */
            actor_name: string;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: string;
            /** Detail */
            detail: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_import_books_excel_api_admin_books_import_post */
        Body_import_books_excel_api_admin_books_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_audio_api_admin_books__book_id__audio_post */
        Body_upload_audio_api_admin_books__book_id__audio_post: {
            /** File */
            file: string;
        };
        /** Body_upload_cover_api_admin_books__book_id__cover_post */
        Body_upload_cover_api_admin_books__book_id__cover_post: {
            /** File */
            file: string;
        };
        /** BookCreateRequest */
        BookCreateRequest: {
            /**
             * Isbn
             * @description ISBN；无 ISBN 书目传空
             */
            isbn?: string | null;
            /** Title */
            title: string;
            /**
             * Author
             * @default
             */
            author: string;
            /** Word Count */
            word_count: number;
            /** Ar Level */
            ar_level?: string | null;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Grade
             * @default
             */
            grade: string;
            /** Description */
            description?: string | null;
            /**
             * Copy Count
             * @description 入库副本数（默认1）
             * @default 1
             */
            copy_count: number;
        };
        /** BookResponse */
        BookResponse: {
            /** Id */
            id: number;
            /** Isbn */
            isbn: string | null;
            /** Internal Code */
            internal_code: string | null;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Cover Path */
            cover_path: string | null;
            /** Audio Path */
            audio_path: string | null;
            /** Audio Duration Seconds */
            audio_duration_seconds: number | null;
            /** Word Count */
            word_count: number;
            /** Ar Level */
            ar_level: string | null;
            /** Topic */
            topic: string;
            /** Grade */
            grade: string;
            /** Description */
            description: string | null;
            /** Status */
            status: number;
            /**
             * Copy Count
             * @description 在册副本总数
             * @default 0
             */
            copy_count: number;
        };
        /** BookUpdateRequest */
        BookUpdateRequest: {
            /** Title */
            title: string;
            /**
             * Author
             * @default
             */
            author: string;
            /** Word Count */
            word_count: number;
            /** Ar Level */
            ar_level?: string | null;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Grade
             * @default
             */
            grade: string;
            /** Description */
            description?: string | null;
        };
        /** BorrowRecordResponse */
        BorrowRecordResponse: {
            /** Id */
            id: number;
            /** Child Id */
            child_id: number;
            /** Copy Id */
            copy_id: number;
            /** Book Id */
            book_id: number;
            /**
             * Borrowed At
             * Format: date-time
             */
            borrowed_at: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Returned At */
            returned_at: string | null;
            /** Status */
            status: string;
            /** Renew Used */
            renew_used: number;
            /** Override Reason */
            override_reason: string | null;
            /**
             * Warnings
             * @description 借书软提示（AR 超范围等，不拦截）
             * @default []
             */
            warnings: string[];
        };
        /** BorrowRequest */
        BorrowRequest: {
            /** Child Id */
            child_id: number;
            /**
             * Isbn
             * @description 扫 ISBN 借书
             */
            isbn?: string | null;
            /**
             * Copy Id
             * @description 指定副本
             */
            copy_id?: number | null;
            /**
             * Override Reason
             * @description 人工放行原因（异常借书）
             */
            override_reason?: string | null;
        };
        /** ChildCardResponse */
        ChildCardResponse: {
            /** Child Id */
            child_id: number;
            /** Name */
            name: string;
            /** English Name */
            english_name: string | null;
            /** Member Status */
            member_status: string;
            /** Parent Name */
            parent_name: string;
            /** Parent Phone */
            parent_phone: string;
            /** Active Borrows */
            active_borrows: number;
            /** Overdue Count */
            overdue_count: number;
            /** Available Quota */
            available_quota: number;
            /** Borrow Limit */
            borrow_limit: number;
            /** Deposit Status */
            deposit_status: string;
            /** Deposit Available */
            deposit_available: string;
            /** Records */
            records: components["schemas"]["BorrowRecordResponse"][];
        };
        /** ChildCreateRequest */
        ChildCreateRequest: {
            /** Name */
            name: string;
            /** English Name */
            english_name?: string | null;
            /** Gender */
            gender?: number | null;
            /** Birthday */
            birthday?: string | null;
            /**
             * Grade
             * @default
             */
            grade: string;
        };
        /** ChildResponse */
        ChildResponse: {
            /** Id */
            id: number;
            /** Parent Id */
            parent_id: number;
            /** Name */
            name: string;
            /** English Name */
            english_name: string | null;
            /** Gender */
            gender: number | null;
            /** Birthday */
            birthday: string | null;
            /** Grade */
            grade: string;
            /** Member Status */
            member_status: string;
            /** Member Start */
            member_start: string | null;
            /** Member Expire */
            member_expire: string | null;
        };
        /** ChildWithParentResponse */
        ChildWithParentResponse: {
            /** Id */
            id: number;
            /** Parent Id */
            parent_id: number;
            /** Name */
            name: string;
            /** English Name */
            english_name: string | null;
            /** Gender */
            gender: number | null;
            /** Birthday */
            birthday: string | null;
            /** Grade */
            grade: string;
            /** Member Status */
            member_status: string;
            /** Member Start */
            member_start: string | null;
            /** Member Expire */
            member_expire: string | null;
            /**
             * Parent Name
             * @default
             */
            parent_name: string;
            /**
             * Parent Phone
             * @default
             */
            parent_phone: string;
        };
        /** CopyResponse */
        CopyResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Copy Code */
            copy_code: string;
            /** Status */
            status: string;
        };
        /** CopyStatusUpdateRequest */
        CopyStatusUpdateRequest: {
            /**
             * Status
             * @description 新状态
             */
            status: string;
            /**
             * Reason
             * @description 操作原因（留痕）
             */
            reason: string;
        };
        /** DashboardOverviewResponse */
        DashboardOverviewResponse: {
            /** Admin Count */
            admin_count: number;
            /** Today Logins */
            today_logins: number;
            /** Config Count */
            config_count: number;
            /** Recent Config Changes */
            recent_config_changes: components["schemas"]["DashboardRecentChange"][];
        };
        /** DashboardRecentChange */
        DashboardRecentChange: {
            /** Config Name */
            config_name: string;
            /** Change */
            change: string;
            /** Actor Name */
            actor_name: string;
            /** Created At */
            created_at: string;
        };
        /** DeductRequest */
        DeductRequest: {
            /**
             * Amount
             * @description 赔偿金额（元）
             */
            amount: string;
            /**
             * Reason
             * @description 事由（关联图书等，留痕）
             */
            reason: string;
            /**
             * Copy Id
             * @description 关联副本ID
             */
            copy_id?: number | null;
        };
        /** DepositLedgerResponse */
        DepositLedgerResponse: {
            /** Id */
            id: number;
            /** Entry Type */
            entry_type: string;
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /** Reason */
            reason: string;
            /** Related Copy Id */
            related_copy_id: number | null;
            /**
             * Create Time
             * Format: date-time
             */
            create_time: string;
        };
        /** DepositResponse */
        DepositResponse: {
            /** Id */
            id: number;
            /** Child Id */
            child_id: number;
            /**
             * Child Name
             * @default
             */
            child_name: string;
            /** Amount */
            amount: string;
            /** Available Amount */
            available_amount: string;
            /** Deducted Amount */
            deducted_amount: string;
            /** Supplemented Total */
            supplemented_total: string;
            /** Status */
            status: string;
            /** Unpaid Balance */
            unpaid_balance: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResultResponse */
        ImportResultResponse: {
            /** Total Rows */
            total_rows: number;
            /** Success Count */
            success_count: number;
            /** Failed Count */
            failed_count: number;
            /**
             * Errors
             * @description 行号+原因
             */
            errors?: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["AdminUserResponse"];
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["AdminUserResponse"];
            /** Permissions */
            permissions: string[];
        };
        /** OrderConfirmRequest */
        OrderConfirmRequest: {
            /**
             * Pay Method
             * @description 收款方式
             */
            pay_method: string;
            /**
             * Remark
             * @description 凭证说明（留痕）
             * @default
             */
            remark: string;
        };
        /** OrderCreateRequest */
        OrderCreateRequest: {
            /** Order Type */
            order_type: string;
            /** Child Id */
            child_id: number;
            /**
             * Remark
             * @default
             */
            remark: string;
        };
        /** OrderResponse */
        OrderResponse: {
            /** Id */
            id: number;
            /** Order No */
            order_no: string;
            /** Order Type */
            order_type: string;
            /** Parent Id */
            parent_id: number;
            /** Child Id */
            child_id: number | null;
            /** Amount */
            amount: string;
            /** Status */
            status: string;
            /** Pay Method */
            pay_method: string | null;
            /** Paid At */
            paid_at: string | null;
            /** Remark */
            remark: string;
            /**
             * Create Time
             * Format: date-time
             */
            create_time: string;
            /** Child Name */
            child_name?: string | null;
            /** Parent Name */
            parent_name?: string | null;
        };
        /** OverdueItemResponse */
        OverdueItemResponse: {
            /** Record Id */
            record_id: number;
            /** Child Name */
            child_name: string;
            /** Parent Phone */
            parent_phone: string;
            /** Book Title */
            book_title: string;
            /** Copy Code */
            copy_code: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Days Overdue */
            days_overdue: number;
        };
        /** PaginatedResponse[AuditLogResponse] */
        PaginatedResponse_AuditLogResponse_: {
            /**
             * Items
             * @description 数据列表
             */
            items?: components["schemas"]["AuditLogResponse"][];
            /**
             * Total
             * @description 总数
             * @default 0
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             * @default 20
             */
            page_size: number;
            /**
             * Has Next
             * @description 是否有下一页
             * @default false
             */
            has_next: boolean;
        };
        /** PaginatedResponse[BookResponse] */
        PaginatedResponse_BookResponse_: {
            /**
             * Items
             * @description 数据列表
             */
            items?: components["schemas"]["BookResponse"][];
            /**
             * Total
             * @description 总数
             * @default 0
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             * @default 20
             */
            page_size: number;
            /**
             * Has Next
             * @description 是否有下一页
             * @default false
             */
            has_next: boolean;
        };
        /** PaginatedResponse[ChildWithParentResponse] */
        PaginatedResponse_ChildWithParentResponse_: {
            /**
             * Items
             * @description 数据列表
             */
            items?: components["schemas"]["ChildWithParentResponse"][];
            /**
             * Total
             * @description 总数
             * @default 0
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             * @default 20
             */
            page_size: number;
            /**
             * Has Next
             * @description 是否有下一页
             * @default false
             */
            has_next: boolean;
        };
        /** PaginatedResponse[DepositResponse] */
        PaginatedResponse_DepositResponse_: {
            /**
             * Items
             * @description 数据列表
             */
            items?: components["schemas"]["DepositResponse"][];
            /**
             * Total
             * @description 总数
             * @default 0
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             * @default 20
             */
            page_size: number;
            /**
             * Has Next
             * @description 是否有下一页
             * @default false
             */
            has_next: boolean;
        };
        /** PaginatedResponse[OrderResponse] */
        PaginatedResponse_OrderResponse_: {
            /**
             * Items
             * @description 数据列表
             */
            items?: components["schemas"]["OrderResponse"][];
            /**
             * Total
             * @description 总数
             * @default 0
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             * @default 20
             */
            page_size: number;
            /**
             * Has Next
             * @description 是否有下一页
             * @default false
             */
            has_next: boolean;
        };
        /** ParentCreateRequest */
        ParentCreateRequest: {
            /** Name */
            name: string;
            /**
             * Phone
             * @description 手机号（11位）
             */
            phone: string;
            /**
             * Remark
             * @default
             */
            remark: string;
        };
        /** ParentResponse */
        ParentResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Remark */
            remark: string;
        };
        /** QuizQuestionCreateRequest */
        QuizQuestionCreateRequest: {
            /**
             * Question Type
             * @default single
             */
            question_type: string;
            /** Question Text */
            question_text: string;
            /** Options */
            options: string[];
            /** Answer */
            answer: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** QuizQuestionResponse */
        QuizQuestionResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Question Type */
            question_type: string;
            /** Question Text */
            question_text: string;
            /** Options */
            options: string[];
            /** Answer */
            answer: string;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: number;
        };
        /** RenewRequest */
        RenewRequest: {
            /** Record Id */
            record_id: number;
        };
        /** ReturnRequest */
        ReturnRequest: {
            /** Copy Id */
            copy_id: number;
            /**
             * Condition
             * @default normal
             */
            condition: string;
        };
        /** SystemConfigResponse */
        SystemConfigResponse: {
            /** Id */
            id: number;
            /** Config Key */
            config_key: string;
            /** Display Name */
            display_name: string;
            /** Config Value */
            config_value: string;
            /** Default Value */
            default_value: string;
            /** Value Type */
            value_type: string;
            /** Category */
            category: string;
            /** Description */
            description: string;
        };
        /** SystemConfigUpdateRequest */
        SystemConfigUpdateRequest: {
            /**
             * Value
             * @description 新值（字符串，服务端按类型解析）
             */
            value: string;
            /**
             * Reason
             * @description 变更原因（必填留痕）
             */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_configs_api_admin_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfigResponse"][];
                };
            };
        };
    };
    update_config_api_admin_configs__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_admin_audit_logs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                actor_id?: number | null;
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_AuditLogResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_overview_api_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
        };
    };
    list_books_api_admin_books_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                keyword?: string | null;
                ar_pending?: boolean;
                status?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_BookResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_book_api_admin_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_admin_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_book_api_admin_books__book_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_copies_api_admin_books__book_id__copies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_copies_api_admin_books__book_id__copies_post: {
        parameters: {
            query: {
                count: number;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_book_status_api_admin_books__book_id__toggle_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_copy_status_api_admin_copies__copy_id__status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                copy_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cover_api_admin_books__book_id__cover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cover_api_admin_books__book_id__cover_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_audio_api_admin_books__book_id__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_audio_api_admin_books__book_id__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_books_excel_api_admin_books_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_books_excel_api_admin_books_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_upload_api_admin_uploads__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_admin_books__book_id__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizQuestionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_admin_books__book_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizQuestionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_question_api_admin_questions__question_id__toggle_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_api_admin_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    child_card_api_admin_circulation_children__child_id__card_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    borrow_book_api_admin_circulation_borrow_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BorrowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorrowRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    return_book_api_admin_circulation_return_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorrowRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_book_api_admin_circulation_renew_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorrowRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_list_api_admin_circulation_overdue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverdueItemResponse"][];
                };
            };
        };
    };
    create_parent_api_admin_members_parents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_children_api_admin_members_parents__parent_id__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_child_api_admin_members_parents__parent_id__children_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parent_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_children_page_api_admin_members_children_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                keyword?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ChildWithParentResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_admin_orders_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                keyword?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_OrderResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_admin_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_payment_api_admin_orders__order_id__confirm_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_admin_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deposits_api_admin_deposits_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                keyword?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DepositResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deposit_api_admin_deposits_children__child_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deposit_ledgers_api_admin_deposits_children__child_id__ledgers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositLedgerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deposit_order_api_admin_deposits_children__child_id__orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplement_order_api_admin_deposits_children__child_id__supplement_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deduct_deposit_api_admin_deposits_children__child_id__deduct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeductRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
