"""wm1 admin tables

Revision ID: 108ab33759d5
Revises:
Create Date: 2026-08-22 11:34:08.551135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "108ab33759d5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("username", sa.String(length=191), nullable=False, comment="登录名"),
        sa.Column("password_hash", sa.String(length=255), nullable=False, comment="密码哈希"),
        sa.Column("display_name", sa.String(length=64), nullable=False, comment="显示名"),
        sa.Column("role", sa.String(length=20), nullable=False, comment="角色: superadmin/staff"),
        sa.Column("status", sa.SmallInteger(), nullable=False, comment="1=启用 0=禁用"),
        sa.Column(
            "token_generation", sa.Integer(), nullable=False, comment="改密后+1，旧token失效"
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True, comment="最近登录时间"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_username"), "admin_users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.BigInteger(), nullable=False, comment="操作人ID"),
        sa.Column("actor_name", sa.String(length=64), nullable=False, comment="操作人名"),
        sa.Column("action", sa.String(length=100), nullable=False, comment="动作"),
        sa.Column("target_type", sa.String(length=50), nullable=False, comment="对象类型"),
        sa.Column("target_id", sa.String(length=64), nullable=False, comment="对象标识"),
        sa.Column("detail", sa.Text(), nullable=True, comment="详情JSON（含变更前后值）"),
        sa.Column("reason", sa.String(length=500), nullable=False, comment="操作原因"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="操作时间"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_table(
        "system_configs",
        sa.Column("config_key", sa.String(length=191), nullable=False, comment="配置键"),
        sa.Column(
            "config_value",
            sa.String(length=500),
            nullable=False,
            comment="配置值（字符串存储，按类型解析）",
        ),
        sa.Column("default_value", sa.String(length=500), nullable=False, comment="默认值"),
        sa.Column("value_type", sa.String(length=10), nullable=False, comment="值类型"),
        sa.Column(
            "category", sa.String(length=50), nullable=False, comment="分类（借阅/收费/测验…）"
        ),
        sa.Column("description", sa.String(length=200), nullable=False, comment="说明"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_configs_config_key"), "system_configs", ["config_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_configs_config_key"), table_name="system_configs")
    op.drop_table("system_configs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_admin_users_username"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
