"""t20c handled_at comment refresh

Revision ID: 10d43873633c
Revises: a3b5c7d9e1f3
Create Date: 2026-09-06 14:46:07.321579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "10d43873633c"
down_revision: Union[str, Sequence[str], None] = "a3b5c7d9e1f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_notifications",
        "handled_at",
        existing_type=mysql.DATETIME(),
        comment="人工标记处理时间（T20c：优先于机器推导显示态）",
        existing_comment="审计：处理时间（不参与显示态）",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_notifications",
        "handled_at",
        existing_type=mysql.DATETIME(),
        comment="审计：处理时间（不参与显示态）",
        existing_comment="人工标记处理时间（T20c：优先于机器推导显示态）",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
