"""wm4 deposit tables

Revision ID: 265a7ba6645d
Revises: 540436252807
Create Date: 2026-08-22 20:27:19.988397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "265a7ba6645d"
down_revision: Union[str, Sequence[str], None] = "540436252807"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_ledgers",
        sa.Column("deposit_id", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="发生额（正数；方向由类型定）",
        ),
        sa.Column(
            "balance_after",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="发生后可用余额",
        ),
        sa.Column(
            "reason", sa.String(length=200), nullable=False, comment="事由（赔偿关联图书等）"
        ),
        sa.Column("related_copy_id", sa.Integer(), nullable=True, comment="关联副本（赔偿时）"),
        sa.Column("operator_id", sa.Integer(), nullable=True, comment="操作管理员"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deposit_ledgers_deposit_id"), "deposit_ledgers", ["deposit_id"], unique=False
    )
    op.create_table(
        "deposits",
        sa.Column("child_id", sa.Integer(), nullable=False, comment="孩子ID（一人一份）"),
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="押金标准额（配置值）",
        ),
        sa.Column(
            "available_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="可用余额（退会退这个）",
        ),
        sa.Column(
            "deducted_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="累计扣除（不退）",
        ),
        sa.Column(
            "supplemented_total",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="累计补缴",
        ),
        sa.Column("status", sa.String(length=24), nullable=False, comment="押金状态"),
        sa.Column(
            "unpaid_balance",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="待结清（扣除超出部分）",
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deposits_child_id"), "deposits", ["child_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deposits_child_id"), table_name="deposits")
    op.drop_table("deposits")
    op.drop_index(op.f("ix_deposit_ledgers_deposit_id"), table_name="deposit_ledgers")
    op.drop_table("deposit_ledgers")
    # ### end Alembic commands ###
