"""wm5 drop uq_active_borrow

Revision ID: 362eb9327df9
Revises: 4898c3d47de4
Create Date: 2026-08-22 20:37:49.643741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "362eb9327df9"
down_revision: Union[str, Sequence[str], None] = "4898c3d47de4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
