"""wm2 catalog tables

Revision ID: 3e0d428f18e0
Revises: 62d92a8cc344
Create Date: 2026-08-22 19:43:34.774619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e0d428f18e0"
down_revision: Union[str, Sequence[str], None] = "62d92a8cc344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_copies",
        sa.Column("book_id", sa.Integer(), nullable=False, comment="书目ID"),
        sa.Column("copy_code", sa.String(length=40), nullable=False, comment="副本码（内部唯一）"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="副本状态"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_copies_book_id"), "book_copies", ["book_id"], unique=False)
    op.create_index("uq_copy_code", "book_copies", ["copy_code", "is_deleted"], unique=True)
    op.create_table(
        "books",
        sa.Column("isbn", sa.String(length=20), nullable=True, comment="ISBN（无 ISBN 为空）"),
        sa.Column(
            "internal_code",
            sa.String(length=30),
            nullable=True,
            comment="内部编号（无 ISBN 书目自动生成）",
        ),
        sa.Column("title", sa.String(length=200), nullable=False, comment="书名"),
        sa.Column("author", sa.String(length=100), nullable=False, comment="作者"),
        sa.Column(
            "cover_path",
            sa.String(length=255),
            nullable=True,
            comment="封面存储路径（服务端统一转 JPG）",
        ),
        sa.Column("audio_path", sa.String(length=255), nullable=True, comment="音频 MP3 路径"),
        sa.Column(
            "audio_duration_seconds", sa.Integer(), nullable=True, comment="音频总时长（秒）"
        ),
        sa.Column("word_count", sa.Integer(), nullable=False, comment="总词数（有效词数入账依据）"),
        sa.Column("ar_level", sa.String(length=10), nullable=True, comment="AR 值（可后补）"),
        sa.Column("topic", sa.String(length=50), nullable=False, comment="主题分类"),
        sa.Column("grade", sa.String(length=50), nullable=False, comment="适读年级"),
        sa.Column("description", sa.Text(), nullable=True, comment="简介"),
        sa.Column("status", sa.SmallInteger(), nullable=False, comment="1=上架 0=下架"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("internal_code"),
    )
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.create_table(
        "quiz_questions",
        sa.Column("book_id", sa.Integer(), nullable=False, comment="书目ID"),
        sa.Column("question_type", sa.String(length=10), nullable=False, comment="题型"),
        sa.Column("question_text", sa.Text(), nullable=False, comment="题干"),
        sa.Column(
            "options",
            sa.Text(),
            nullable=False,
            comment="选项 JSON 数组（单选4项；判断为 [对,错]）",
        ),
        sa.Column(
            "answer",
            sa.String(length=200),
            nullable=False,
            comment="正确答案（单选=选项值；判断=对/错）",
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序（首期取前5）"),
        sa.Column("is_active", sa.SmallInteger(), nullable=False, comment="1=启用 0=停用"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_questions_book_id"), "quiz_questions", ["book_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_questions_book_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_table("books")
    op.drop_index("uq_copy_code", table_name="book_copies")
    op.drop_index(op.f("ix_book_copies_book_id"), table_name="book_copies")
    op.drop_table("book_copies")
    # ### end Alembic commands ###
