"""wm5 borrow tables

Revision ID: 4898c3d47de4
Revises: 265a7ba6645d
Create Date: 2026-08-22 20:35:20.525459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4898c3d47de4"
down_revision: Union[str, Sequence[str], None] = "265a7ba6645d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borrow_records",
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("copy_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("borrowed_at", sa.DateTime(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False, comment="到期日"),
        sa.Column("returned_at", sa.DateTime(), nullable=True),
        sa.Column(
            "returned_condition",
            sa.String(length=20),
            nullable=True,
            comment="归还状态 normal/maintenance/lost",
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("renew_used", sa.Integer(), nullable=False, comment="已用续借次数（上限1）"),
        sa.Column("borrowed_by", sa.Integer(), nullable=True, comment="办理借书的馆员ID"),
        sa.Column(
            "override_reason",
            sa.String(length=200),
            nullable=True,
            comment="人工放行原因（异常借书留痕）",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_borrow_records_book_id"), "borrow_records", ["book_id"], unique=False)
    op.create_index(
        op.f("ix_borrow_records_child_id"), "borrow_records", ["child_id"], unique=False
    )
    op.create_index(op.f("ix_borrow_records_copy_id"), "borrow_records", ["copy_id"], unique=False)
    op.create_index(op.f("ix_borrow_records_status"), "borrow_records", ["status"], unique=False)
    op.create_index("uq_active_borrow", "borrow_records", ["copy_id", "is_deleted"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_active_borrow", table_name="borrow_records")
    op.drop_index(op.f("ix_borrow_records_status"), table_name="borrow_records")
    op.drop_index(op.f("ix_borrow_records_copy_id"), table_name="borrow_records")
    op.drop_index(op.f("ix_borrow_records_child_id"), table_name="borrow_records")
    op.drop_index(op.f("ix_borrow_records_book_id"), table_name="borrow_records")
    op.drop_table("borrow_records")
    # ### end Alembic commands ###
