"""wm3 identity tables

Revision ID: 540436252807
Revises: 3e0d428f18e0
Create Date: 2026-08-22 20:01:33.302987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "540436252807"
down_revision: Union[str, Sequence[str], None] = "3e0d428f18e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "children",
        sa.Column("parent_id", sa.Integer(), nullable=False, comment="家长ID"),
        sa.Column("name", sa.String(length=64), nullable=False, comment="姓名"),
        sa.Column(
            "english_name", sa.String(length=64), nullable=True, comment="英文名（榜单展示用）"
        ),
        sa.Column("avatar", sa.String(length=255), nullable=True, comment="头像"),
        sa.Column("gender", sa.SmallInteger(), nullable=True, comment="1=男 2=女"),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("grade", sa.String(length=50), nullable=False),
        sa.Column(
            "ar_level",
            sa.String(length=10),
            nullable=True,
            comment="当前 AR 值（老师维护，只升不降）",
        ),
        sa.Column("member_status", sa.String(length=24), nullable=False, comment="会员状态"),
        sa.Column("member_start", sa.Date(), nullable=True, comment="会员开始日"),
        sa.Column("member_expire", sa.Date(), nullable=True, comment="会员到期日"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_children_member_status"), "children", ["member_status"], unique=False)
    op.create_index(op.f("ix_children_parent_id"), "children", ["parent_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("order_no", sa.String(length=32), nullable=False, comment="订单号"),
        sa.Column("order_type", sa.String(length=24), nullable=False, comment="订单类型"),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=True, comment="孩子ID（活动费可能家长级）"),
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="实收金额（Decimal 铁律）",
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "pay_method",
            sa.String(length=24),
            nullable=True,
            comment="收款方式（wechat/scan/alipay/transfer/card/cash）",
        ),
        sa.Column("paid_at", sa.DateTime(), nullable=True, comment="收款确认时间"),
        sa.Column("paid_by", sa.Integer(), nullable=True, comment="确认收款的管理员ID"),
        sa.Column("remark", sa.String(length=200), nullable=False, comment="备注/凭证说明"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_child_id"), "orders", ["child_id"], unique=False)
    op.create_index(op.f("ix_orders_order_type"), "orders", ["order_type"], unique=False)
    op.create_index(op.f("ix_orders_parent_id"), "orders", ["parent_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index("uq_order_no", "orders", ["order_no", "is_deleted"], unique=True)
    op.create_table(
        "parents",
        sa.Column("name", sa.String(length=64), nullable=False, comment="家长姓名"),
        sa.Column("phone", sa.String(length=20), nullable=False, comment="手机号（唯一）"),
        sa.Column("wechat_openid", sa.String(length=64), nullable=True, comment="微信 openid"),
        sa.Column("remark", sa.String(length=200), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wechat_openid"),
    )
    op.create_index(op.f("ix_parents_phone"), "parents", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parents_phone"), table_name="parents")
    op.drop_table("parents")
    op.drop_index("uq_order_no", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_parent_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_type"), table_name="orders")
    op.drop_index(op.f("ix_orders_child_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_children_parent_id"), table_name="children")
    op.drop_index(op.f("ix_children_member_status"), table_name="children")
    op.drop_table("children")
    # ### end Alembic commands ###
