"""wm1 add config display_name

Revision ID: 62d92a8cc344
Revises: 108ab33759d5
Create Date: 2026-08-22 19:32:50.094562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "62d92a8cc344"
down_revision: Union[str, Sequence[str], None] = "108ab33759d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_configs",
        sa.Column(
            "display_name", sa.String(length=100), nullable=False, comment="中文显示名（店长视角）"
        ),
    )
    op.alter_column(
        "system_configs",
        "config_key",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=191),
        comment="配置键（系统标识）",
        existing_comment="配置键",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_configs",
        "config_key",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=191),
        comment="配置键",
        existing_comment="配置键（系统标识）",
        existing_nullable=False,
    )
    op.drop_column("system_configs", "display_name")
    # ### end Alembic commands ###
