"""wm6 reading tables

Revision ID: 92e6434da8d1
Revises: 362eb9327df9
Create Date: 2026-08-22 20:42:42.512626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92e6434da8d1"
down_revision: Union[str, Sequence[str], None] = "362eb9327df9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkins",
        sa.Column("book_id", sa.Integer(), nullable=False, comment="触发打卡的书"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False, comment="打卡时的连续天数"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("checkin_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_checkins_child_id"), "checkins", ["child_id"], unique=False)
    op.create_table(
        "reading_progress",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("intervals", sa.Text(), nullable=False, comment="已合并播放区间 JSON"),
        sa.Column("coverage_seconds", sa.Integer(), nullable=False, comment="累计覆盖秒数（并集）"),
        sa.Column("total_seconds", sa.Integer(), nullable=False, comment="音频总时长"),
        sa.Column("finished", sa.Integer(), nullable=False, comment="1=已完播"),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "last_position", sa.Integer(), nullable=False, comment="上次播放位置（断点续播）"
        ),
        sa.Column(
            "last_report_at",
            sa.DateTime(),
            nullable=True,
            comment="上次上报时间（防刷：服务端墙上时钟基准）",
        ),
        sa.Column(
            "reading_minutes",
            sa.Integer(),
            nullable=False,
            comment="阅读时长（=音频原始时长，首次完播记一次）",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_progress_book_id"), "reading_progress", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_reading_progress_child_id"), "reading_progress", ["child_id"], unique=False
    )
    op.create_table(
        "reservations",
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("copy_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="锁定截止（72h）"),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column(
            "is_deleted", sa.SmallInteger(), nullable=True, comment="软删除标记: 0=正常 1=已删除"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservations_book_id"), "reservations", ["book_id"], unique=False)
    op.create_index(op.f("ix_reservations_child_id"), "reservations", ["child_id"], unique=False)
    op.create_index(op.f("ix_reservations_status"), "reservations", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservations_status"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_child_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_book_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_reading_progress_child_id"), table_name="reading_progress")
    op.drop_index(op.f("ix_reading_progress_book_id"), table_name="reading_progress")
    op.drop_table("reading_progress")
    op.drop_index(op.f("ix_checkins_child_id"), table_name="checkins")
    op.drop_table("checkins")
    # ### end Alembic commands ###
